config/routes.rb
Healthstats::Application.routes.draw do
  resources :running_measurements

  get "body_measurements/viz"
  resources :body_measurements

end

app/models/body_measurement.rb
class BodyMeasurement < ActiveRecord::Base
end

app/models/running_measurement.rb
class RunningMeasurement < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/body_measurements_controller.rb
class BodyMeasurementsController < ApplicationController
  before_action :set_body_measurement, only: [:show, :edit, :update, :destroy]

  # GET /body_measurements
  # GET /body_measurements.json
  def index
    @body_measurements = BodyMeasurement.all
  end

  # GET /body_measurements/1
  # GET /body_measurements/1.json
  def show
  end

  # GET /body_measurements/new
  def new
    @body_measurement = BodyMeasurement.new
  end

  # GET /body_measurements/1/edit
  def edit
  end

  # POST /body_measurements
  # POST /body_measurements.json
  def create
    @body_measurement = BodyMeasurement.new(body_measurement_params)

    respond_to do |format|
      if @body_measurement.save
        format.html { redirect_to @body_measurement, notice: 'Body measurement was successfully created.' }
        format.json { render action: 'show', status: :created, location: @body_measurement }
      else
        format.html { render action: 'new' }
        format.json { render json: @body_measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /body_measurements/1
  # PATCH/PUT /body_measurements/1.json
  def update
    respond_to do |format|
      if @body_measurement.update(body_measurement_params)
        format.html { redirect_to @body_measurement, notice: 'Body measurement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @body_measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /body_measurements/1
  # DELETE /body_measurements/1.json
  def destroy
    @body_measurement.destroy
    respond_to do |format|
      format.html { redirect_to body_measurements_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_body_measurement
      @body_measurement = BodyMeasurement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def body_measurement_params
      params.require(:body_measurement).permit(:measurementDate, :occurrence, :weight, :bodyFat)
    end
end

app/controllers/running_measurements_controller.rb
class RunningMeasurementsController < ApplicationController
  before_action :set_running_measurement, only: [:show, :edit, :update, :destroy]

  # GET /running_measurements
  # GET /running_measurements.json
  def index
    @running_measurements = RunningMeasurement.all
  end

  # GET /running_measurements/1
  # GET /running_measurements/1.json
  def show
  end

  # GET /running_measurements/new
  def new
    @running_measurement = RunningMeasurement.new
  end

  # GET /running_measurements/1/edit
  def edit
  end

  # POST /running_measurements
  # POST /running_measurements.json
  def create
    @running_measurement = RunningMeasurement.new(running_measurement_params)

    respond_to do |format|
      if @running_measurement.save
        format.html { redirect_to @running_measurement, notice: 'Running measurement was successfully created.' }
        format.json { render action: 'show', status: :created, location: @running_measurement }
      else
        format.html { render action: 'new' }
        format.json { render json: @running_measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /running_measurements/1
  # PATCH/PUT /running_measurements/1.json
  def update
    respond_to do |format|
      if @running_measurement.update(running_measurement_params)
        format.html { redirect_to @running_measurement, notice: 'Running measurement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @running_measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /running_measurements/1
  # DELETE /running_measurements/1.json
  def destroy
    @running_measurement.destroy
    respond_to do |format|
      format.html { redirect_to running_measurements_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_running_measurement
      @running_measurement = RunningMeasurement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def running_measurement_params
      params.require(:running_measurement).permit(:distance_miles, :duration_seconds, :calories)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/body_measurements_helper.rb
module BodyMeasurementsHelper
end

app/helpers/running_measurements_helper.rb
module RunningMeasurementsHelper
end

app/views/body_measurements/_form.html.erb
<%= form_for(@body_measurement) do |f| %>
  <% if @body_measurement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@body_measurement.errors.count, "error") %> prohibited this body_measurement from being saved:</h2>

      <ul>
      <% @body_measurement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :measurementDate %><br>
    <%= f.date_select :measurementDate %>
  </div>
  <div class="field">
    <%= f.label :occurrence %><br>
    <%= f.number_field :occurrence %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :bodyFat %><br>
    <%= f.text_field :bodyFat %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/body_measurements/edit.html.erb
<h1>Editing body_measurement</h1>

<%= render 'form' %>

<%= link_to 'Show', @body_measurement %> |
<%= link_to 'Back', body_measurements_path %>

app/views/body_measurements/index.html.erb
<h1>Listing body_measurements</h1>

<table>
  <thead>
    <tr>
      <th>Measurementdate</th>
      <th>Occurrence</th>
      <th>Weight</th>
      <th>Bodyfat</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @body_measurements.each do |body_measurement| %>
      <tr>
        <td><%= body_measurement.measurementDate %></td>
        <td><%= body_measurement.occurrence %></td>
        <td><%= body_measurement.weight %></td>
        <td><%= body_measurement.bodyFat %></td>
        <td><%= link_to 'Show', body_measurement %></td>
        <td><%= link_to 'Edit', edit_body_measurement_path(body_measurement) %></td>
        <td><%= link_to 'Destroy', body_measurement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Body measurement', new_body_measurement_path %>

app/views/body_measurements/new.html.erb
<h1>New body_measurement</h1>

<%= render 'form' %>

<%= link_to 'Back', body_measurements_path %>

app/views/body_measurements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Measurementdate:</strong>
  <%= @body_measurement.measurementDate %>
</p>

<p>
  <strong>Occurrence:</strong>
  <%= @body_measurement.occurrence %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @body_measurement.weight %>
</p>

<p>
  <strong>Bodyfat:</strong>
  <%= @body_measurement.bodyFat %>
</p>

<%= link_to 'Edit', edit_body_measurement_path(@body_measurement) %> |
<%= link_to 'Back', body_measurements_path %>

app/views/body_measurements/viz.html.erb
<!DOCTYPE html>
<meta charset="utf-8">
<style>

body {
  font: 10px sans-serif;
}

.axis path,
.axis line {
  fill: none;
  stroke: #000;
  shape-rendering: crispEdges;
}

.x.axis path {
  display: none;
}

.line {
  fill: none;
  stroke: steelblue;
  stroke-width: 1.5px;
}

.line2 {
  fill: none;
  stroke: green;
  stroke-width: 1.5px;
}


</style>
<body>
<script src="http://d3js.org/d3.v3.js"></script>
<script>

var margin = {top: 20, right: 20, bottom: 30, left: 50},
    width = 930 - margin.left - margin.right,
    height = 500 - margin.top - margin.bottom;

var parseDate = d3.time.format("%Y-%m-%d").parse;

var x = d3.time.scale()
    .range([0, width]);

var yWeight = d3.scale.linear()
    .range([height, 0]);

var yBf = d3.scale.linear()
    .range([height, 0]);

var xAxis = d3.svg.axis()
    .scale(x)
    .orient("bottom");

var yAxisWeight = d3.svg.axis()
    .scale(yWeight)
    .orient("left");

var yAxisBf = d3.svg.axis()
    .scale(yBf)
    .orient("right");


var lineWeight = d3.svg.line()
    .x(function(d) { return x(d.measurementDate); })
    .y(function(d) { return yWeight(d.weight); });

var lineBf = d3.svg.line()
    .x(function(d) { return x(d.measurementDate); })
    .y(function(d) { return yBf(d.bodyFat); });


var svg = d3.select("body").append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

d3.json("../body_measurements.json", function(error, data) {
  data.forEach(function(d) {
    d.measurementDate = parseDate(d.measurementDate);
  });

  x.domain(d3.extent(data, function(d) { return d.measurementDate; }));
  yWeight.domain(d3.extent(data, function(d) { return d.weight; }));
  yBf.domain(d3.extent(data, function(d) { return d.bodyFat; }));


  svg.append("g")
      .attr("class", "x axis")
      .attr("transform", "translate(0," + height + ")")
      .call(xAxis);

  svg.append("g")
      .attr("class", "y axis")
      .call(yAxisWeight)
    .append("text")
      .attr("transform", "rotate(-90)")
      .attr("y", 6)
      .attr("dy", ".71em")
      .style("text-anchor", "end")
      .text("Weight");

  svg.append("g")
      .attr("class", "y axis axisRight")
      .attr("transform","translate(" + (width + 0) + ",0)")
      .call(yAxisBf)
    .append("text")
      .attr("transform", "rotate(90)")
      .attr("y", 6)
      .attr("dy", ".71em")
      .attr("x", 55)
      .style("text-anchor", "end")
      .text("Body Fat %");


  svg.append("path")
      .datum(data)
      .attr("class", "line")
      .attr("d", lineWeight);

  svg.append("path")
      .datum(data)
      .attr("class", "line2")
      .attr("d", lineBf);

});

</script>
<h1>BodyMeasurements#viz</h1>
<p>Find me in app/views/body_measurements/viz.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Healthstats</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/running_measurements/_form.html.erb
<%= form_for(@running_measurement) do |f| %>
  <% if @running_measurement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@running_measurement.errors.count, "error") %> prohibited this running_measurement from being saved:</h2>

      <ul>
      <% @running_measurement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :distance_miles %><br>
    <%= f.text_field :distance_miles %>
  </div>
  <div class="field">
    <%= f.label :duration_seconds %><br>
    <%= f.number_field :duration_seconds %>
  </div>
  <div class="field">
    <%= f.label :calories %><br>
    <%= f.text_field :calories %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/running_measurements/edit.html.erb
<h1>Editing running_measurement</h1>

<%= render 'form' %>

<%= link_to 'Show', @running_measurement %> |
<%= link_to 'Back', running_measurements_path %>

app/views/running_measurements/index.html.erb
<h1>Listing running_measurements</h1>

<table>
  <thead>
    <tr>
      <th>Distance miles</th>
      <th>Duration seconds</th>
      <th>Calories</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @running_measurements.each do |running_measurement| %>
      <tr>
        <td><%= running_measurement.distance_miles %></td>
        <td><%= running_measurement.duration_seconds %></td>
        <td><%= running_measurement.calories %></td>
        <td><%= link_to 'Show', running_measurement %></td>
        <td><%= link_to 'Edit', edit_running_measurement_path(running_measurement) %></td>
        <td><%= link_to 'Destroy', running_measurement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Running measurement', new_running_measurement_path %>

app/views/running_measurements/new.html.erb
<h1>New running_measurement</h1>

<%= render 'form' %>

<%= link_to 'Back', running_measurements_path %>

app/views/running_measurements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Distance miles:</strong>
  <%= @running_measurement.distance_miles %>
</p>

<p>
  <strong>Duration seconds:</strong>
  <%= @running_measurement.duration_seconds %>
</p>

<p>
  <strong>Calories:</strong>
  <%= @running_measurement.calories %>
</p>

<%= link_to 'Edit', edit_running_measurement_path(@running_measurement) %> |
<%= link_to 'Back', running_measurements_path %>